package inputvalidator

var message = map[string]map[string]string{
	"en": map[string]string{
		"invalid-char-found":             "Invalid Character Found",
		"len-is-greater-than-expected":   "Input Length is greater than 20 characters",
		"invalid-length-key":             "Invalid Length of the Key",
		"invalid-email-address":          "Invalid Email Address",
		"email-exists":                   "Email Address is registered with us. Try with Login",
		"len-is-less-than-expected":      "Passwors Length is less than 6 characters",
		"should-not-contain-space":       "Password should not contain space",
		"must-contain-special-char":      "Password must contain atleast one special character",
		"company-name-exist":             "The Company Name is already exists",
		"insert-success":                 "Inserted Successfully",
		"org-insert-failed":              "Organization record Insert failed",
		"user-role-failed":               "Something went wrong during role & user role map creation",
		"age-is-under-limit":             "Age must be above 18 and below 99",
		"dob-invalid":                    "Date of Birth is invalid",
		"invalid-contact":                "The given contact number is invalid",
		"from-date-greater-than-to-date": "The From date must be less than To date",
		"company-name-invalid":           "Please enter valid company name",
		"must-be-valid":                  " Must be valid",
		"future-date":                    "must not be future date",
		"invalid-url":                    "URL is not valid",
		"enter-valid-password":           "Please enter valid password",
		"must-contain-lower-char":        "Password must contain lower case",
	},
	"fr": map[string]string{
		"invalid-char-found":             "Invalid Character Found",
		"len-is-greater-than-expected":   "Input Length is greater than 20 characters",
		"invalid-length-key":             "Invalid Length of the Key",
		"invalid-email-address":          "Invalid Email Address",
		"email-exists":                   "Email Address is registered with us. Try with Login",
		"len-is-less-than-expected":      "Passwors Length is less than 6 characters",
		"should-not-contain-space":       "Password should not contain space",
		"must-contain-special-char":      "Password must contain atleast one special character",
		"company-name-exist":             "The Company Name is already exists",
		"insert-success":                 "Inserted Successfully",
		"org-insert-failed":              "Organization record Insert failed",
		"user-role-failed":               "Something went wrong during role & user role map creation",
		"age-is-under-limit":             "Age must be above 18 and below 99",
		"dob-invalid":                    "Date of Birth is invalid",
		"invalid-contact":                "The given contact number is invalid",
		"from-date-greater-than-to-date": "The From date must be less than To date",
		"company-name-invalid":           "Please enter valid company name",
		"must-be-valid":                  " Must be valid",
		"future-date":                    "must not be future date",
		"invalid-url":                    "URL is not valid",
		"enter-valid-password":           "Please enter valid password",
		"must-contain-lower-char":        "Password must contain lower case",
	},
}
